# Generated by Django 5.0.3 on 2024-03-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phonenumber', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('displayname', models.CharField(max_length=255)),
                ('licensenum', models.CharField(max_length=255)),
                ('vehicleregnum', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Normaluser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phonenumber', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('displayname', models.CharField(max_length=255)),
            ],
        ),
    ]
