# Generated by Django 5.0.2 on 2024-03-17 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rs_auth', '0002_driver_created_at_driver_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleFares',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicleType', models.IntegerField(choices=[(1, 'Auto'), (2, 'Car'), (3, 'Bike')])),
                ('modelName', models.TextField(max_length=50)),
                ('distance', models.IntegerField()),
                ('fare', models.FloatField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
