# Generated by Django 5.0.2 on 2024-03-17 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rs_auth', '0003_vehiclefares'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclefares',
            name='modelName',
        ),
    ]
